### PR TITLE
Add php action workflow

### PR DESCRIPTION
**Pull request by antonfischl1980**
Signed-off-by: Anton Fischl <github@fischl-online.de>

### CODE REVIEW

**Comment by antonfischl1980** [comment]
Just signed CLA

**Comment by antonfischl1980** [comment]
> Thank you for your pull request. Before we can look at it, you'll need to sign a Contributor License Agreement (CLA).
> 
> **Please follow instructions at https://icinga.com/company/contributor-agreement to sign the CLA.**
> 
> After that, please reply here with a comment and we'll verify.
> 
> Contributors that have not signed yet: @antonfischl1980

I just signed the CLA

**Comment by bobapple** [comment]
@cla-bot check

**Comment by martialblog** [comment]
Superseded by #40 

@Thomas-Gelf  Can be closed

**Pull request closed without merging**
